os:
  editPreset: 'nvim-remote'

promptToReturnFromSubprocess: false

git:
  paging:
    colorArg: always
    pager: delta --diff-so-fancy --paging=never
  merging:
    args: "--no-ff"

customCommands:
  - key: b
    command: tig blame -- {{.SelectedFile.Name}}
    context: files
    description: blame file at tree
    subprocess: yes
  - key: b
    command: tig blame {{.SelectedSubCommit.Sha}} -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at revision
    subprocess: yes
  - key: B
    command: tig blame -- {{.SelectedCommitFile.Name}}
    context: commitFiles
    description: blame file at tree
    subprocess: yes
