[icons]
icons = "awesome6"

[theme]
theme = "dracula"
[theme.overrides]
alternating_tint_bg="#111111"

[[block]]
block = "packages"
package_manager = ["pacman", "aur"]
interval = 600
error_interval = 300
format = " $icon $pacman + $aur = $total updates available "
format_singular = " $icon $total update available "
format_up_to_date = " $icon system up to date "
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "paru -Qua"
signal = 1

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
[[block.click]]
button = "left"
cmd = "iwgtk"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "
merge_with_next = true

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $barchart $utilization $frequency "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90
merge_with_next = true

[[block]]
block = "load"
format = " $icon  $1m.eng(w:4) "
interval = 1
merge_with_next = true

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "sound"
format = " $icon { $volume|} "
merge_with_next = true
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "bluetooth"
mac = "70:5A:6F:62:C4:75"
disconnected_format = " $icon "
format = " $icon $name{ $percentage|} "
[block.battery_state]
"0..20" = "critical"
"21..70" = "warning"
"71..100" = "good"
[[block.click]]
button = "left"
cmd = "blueman-manager"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:fr_BE) "
short = " $icon $timestamp.datetime(f:%R) "

[[block]]
block = "battery"
format = " $icon $percentage "
merge_with_next = true

[[block]]
block = "tea_timer"
format = " $icon  {$minutes:$seconds |}"
done_cmd = "notify-send 'Tea time !'"
